keys:
  - &dguibert 3198EB02EB0EEC85FE5BF6AC4E6EE5C219FDD513
  - &dguibert_titan age1gthhn69gtgn8gsvv58xqu9vxfnczl68kktm64638xfv5j3qm4grqeuw0h4
  - &titan age1ejsy39scvjujs392lrrx99cs7qx8j746wcasau2z8jp6h27l3dfsrne8w9
  #rpi41           00064376b1bf4617928161cd5b5318afcd030f01 (20201218)
  - &rpi41 00064376b1bf4617928161cd5b5318afcd030f01
  - &rpi41_age age1lml6xd6l7ntypmtmv7rsqxzguln5puynzlv2yf3k99hrr48l3ppq6nw3t3
  - &rpi31 F7368E72F15D95927F685CD0A264BDA92AE79515
  - &t580 CE0DA0A123AA2DC1E7AA38E0011B75E24664FD1E
creation_rules:
  # dguibert
  - path_regex: homes/dguibert/[^/]+-sec\.nix$
    key_groups:
      - pgp:
          - *dguibert
  # dguibert
  # titan
  - path_regex: hosts/titan/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *titan
  # dguibert
  # rpi41
  - path_regex: hosts/rpi41/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi41
        age:
          - *rpi41_age
  # dguibert
  # rpi31
  - path_regex: hosts/rpi31/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi31
  # dguibert
  # t580
  - path_regex: hosts/laptop-s93efa6b/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *t580
  # dguibert
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi41
          - *rpi31
          - *t580
        age:
          - *titan
          - *rpi41_age
  - path_regex: homes/dguibert/[^/]+-sec\.el$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi41
          - *rpi31
          - *t580
        age:
          - *titan
          - *rpi41_age
