keys:
  - &dguibert 3198EB02EB0EEC85FE5BF6AC4E6EE5C219FDD513
  - &dguibert_titan_age age1gthhn69gtgn8gsvv58xqu9vxfnczl68kktm64638xfv5j3qm4grqeuw0h4
  - &dguibert_t580_age age1zpv9vp6rkcttpg8yk5qk8yjh4kxh6pj9d3uvzfekglth6mfc0drqekue6r
  - &titan_age age1ejsy39scvjujs392lrrx99cs7qx8j746wcasau2z8jp6h27l3dfsrne8w9
  #rpi41           00064376b1bf4617928161cd5b5318afcd030f01 (20201218)
  - &rpi41_age age1lml6xd6l7ntypmtmv7rsqxzguln5puynzlv2yf3k99hrr48l3ppq6nw3t3
  - &rpi31 F7368E72F15D95927F685CD0A264BDA92AE79515
  - &t580_age age1e6up3vv3av0tlsp9lcmfxqga07r6d3ccahzzdp7een7facm5ps0qztps7l
creation_rules:
  # dguibert
  - path_regex: modules/home-manager/dguibert/[^/]+-sec\.nix$
    key_groups:
      - pgp:
          - *dguibert
  # dguibert
  # titan
  - path_regex: hosts/titan/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *titan_age
  # dguibert
  # rpi41
  - path_regex: hosts/rpi41/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *rpi41_age
  # dguibert
  # rpi31
  - path_regex: hosts/rpi31/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi31
  # dguibert
  # t580
  - path_regex: hosts/t580/secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *t580_age
  # dguibert
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi31
        age:
          - *rpi41_age
          - *t580_age
          - *titan_age
  - path_regex: modules/home-manager/dguibert/[^/]+-sec\.el$
    key_groups:
      - pgp:
          - *dguibert
          - *rpi31
        age:
          - *rpi41_age
          - *t580_age
          - *titan_age
  - path_regex: modules/home-manager/dguibert/[^/]+\.yaml$
    key_groups:
      - pgp:
          - *dguibert
        age:
          - *dguibert_titan_age
          - *dguibert_t580_age
